/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class BossFightSynopsisListResponse : TBase
  {
    private BossFightMenuResponse _bossResponse;
    private List<BossFightSynopsisResponse> _synopsisList;

    public BossFightMenuResponse BossResponse
    {
      get
      {
        return _bossResponse;
      }
      set
      {
        __isset.bossResponse = true;
        this._bossResponse = value;
      }
    }

    public List<BossFightSynopsisResponse> SynopsisList
    {
      get
      {
        return _synopsisList;
      }
      set
      {
        __isset.synopsisList = true;
        this._synopsisList = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool bossResponse;
      public bool synopsisList;
    }

    public BossFightSynopsisListResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              BossResponse = new BossFightMenuResponse();
              BossResponse.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                SynopsisList = new List<BossFightSynopsisResponse>();
                TList _list382 = iprot.ReadListBegin();
                for( int _i383 = 0; _i383 < _list382.Count; ++_i383)
                {
                  BossFightSynopsisResponse _elem384 = new BossFightSynopsisResponse();
                  _elem384 = new BossFightSynopsisResponse();
                  _elem384.Read(iprot);
                  SynopsisList.Add(_elem384);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BossFightSynopsisListResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (BossResponse != null && __isset.bossResponse) {
        field.Name = "bossResponse";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        BossResponse.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (SynopsisList != null && __isset.synopsisList) {
        field.Name = "synopsisList";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, SynopsisList.Count));
          foreach (BossFightSynopsisResponse _iter385 in SynopsisList)
          {
            _iter385.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BossFightSynopsisListResponse(");
      sb.Append("BossResponse: ");
      sb.Append(BossResponse== null ? "<null>" : BossResponse.ToString());
      sb.Append(",SynopsisList: ");
      sb.Append(SynopsisList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
