/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class ClanfightPlayerToWayResponse : TBase
  {
    private ClanFightSeatResponse _clanFightSeatResponse;
    private List<ClanFightSimpleFightDataResponse> _simpleFightDataList;
    private ClanFightPlayerMoveResponse _clanFightPlayerMoveResponse;
    private ClanFightPlayerSelfResponse _clanFightPlayerSelfResponse;

    public ClanFightSeatResponse ClanFightSeatResponse
    {
      get
      {
        return _clanFightSeatResponse;
      }
      set
      {
        __isset.clanFightSeatResponse = true;
        this._clanFightSeatResponse = value;
      }
    }

    public List<ClanFightSimpleFightDataResponse> SimpleFightDataList
    {
      get
      {
        return _simpleFightDataList;
      }
      set
      {
        __isset.simpleFightDataList = true;
        this._simpleFightDataList = value;
      }
    }

    public ClanFightPlayerMoveResponse ClanFightPlayerMoveResponse
    {
      get
      {
        return _clanFightPlayerMoveResponse;
      }
      set
      {
        __isset.clanFightPlayerMoveResponse = true;
        this._clanFightPlayerMoveResponse = value;
      }
    }

    public ClanFightPlayerSelfResponse ClanFightPlayerSelfResponse
    {
      get
      {
        return _clanFightPlayerSelfResponse;
      }
      set
      {
        __isset.clanFightPlayerSelfResponse = true;
        this._clanFightPlayerSelfResponse = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool clanFightSeatResponse;
      public bool simpleFightDataList;
      public bool clanFightPlayerMoveResponse;
      public bool clanFightPlayerSelfResponse;
    }

    public ClanfightPlayerToWayResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              ClanFightSeatResponse = new ClanFightSeatResponse();
              ClanFightSeatResponse.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                SimpleFightDataList = new List<ClanFightSimpleFightDataResponse>();
                TList _list849 = iprot.ReadListBegin();
                for( int _i850 = 0; _i850 < _list849.Count; ++_i850)
                {
                  ClanFightSimpleFightDataResponse _elem851 = new ClanFightSimpleFightDataResponse();
                  _elem851 = new ClanFightSimpleFightDataResponse();
                  _elem851.Read(iprot);
                  SimpleFightDataList.Add(_elem851);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              ClanFightPlayerMoveResponse = new ClanFightPlayerMoveResponse();
              ClanFightPlayerMoveResponse.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              ClanFightPlayerSelfResponse = new ClanFightPlayerSelfResponse();
              ClanFightPlayerSelfResponse.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ClanfightPlayerToWayResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ClanFightSeatResponse != null && __isset.clanFightSeatResponse) {
        field.Name = "clanFightSeatResponse";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        ClanFightSeatResponse.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (SimpleFightDataList != null && __isset.simpleFightDataList) {
        field.Name = "simpleFightDataList";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, SimpleFightDataList.Count));
          foreach (ClanFightSimpleFightDataResponse _iter852 in SimpleFightDataList)
          {
            _iter852.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (ClanFightPlayerMoveResponse != null && __isset.clanFightPlayerMoveResponse) {
        field.Name = "clanFightPlayerMoveResponse";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        ClanFightPlayerMoveResponse.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (ClanFightPlayerSelfResponse != null && __isset.clanFightPlayerSelfResponse) {
        field.Name = "clanFightPlayerSelfResponse";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        ClanFightPlayerSelfResponse.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ClanfightPlayerToWayResponse(");
      sb.Append("ClanFightSeatResponse: ");
      sb.Append(ClanFightSeatResponse== null ? "<null>" : ClanFightSeatResponse.ToString());
      sb.Append(",SimpleFightDataList: ");
      sb.Append(SimpleFightDataList);
      sb.Append(",ClanFightPlayerMoveResponse: ");
      sb.Append(ClanFightPlayerMoveResponse== null ? "<null>" : ClanFightPlayerMoveResponse.ToString());
      sb.Append(",ClanFightPlayerSelfResponse: ");
      sb.Append(ClanFightPlayerSelfResponse== null ? "<null>" : ClanFightPlayerSelfResponse.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
