/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class ClanFightEnterInterfaceResponse : TBase
  {
    private string _title;
    private int _attackClan;
    private int _defendClan;
    private List<ClanFightTableResponse> _clanFightTableResponseList;
    private string _clanFightDesc;
    private string _buttonDesc;

    public string Title
    {
      get
      {
        return _title;
      }
      set
      {
        __isset.title = true;
        this._title = value;
      }
    }

    public int AttackClan
    {
      get
      {
        return _attackClan;
      }
      set
      {
        __isset.attackClan = true;
        this._attackClan = value;
      }
    }

    public int DefendClan
    {
      get
      {
        return _defendClan;
      }
      set
      {
        __isset.defendClan = true;
        this._defendClan = value;
      }
    }

    public List<ClanFightTableResponse> ClanFightTableResponseList
    {
      get
      {
        return _clanFightTableResponseList;
      }
      set
      {
        __isset.clanFightTableResponseList = true;
        this._clanFightTableResponseList = value;
      }
    }

    public string ClanFightDesc
    {
      get
      {
        return _clanFightDesc;
      }
      set
      {
        __isset.clanFightDesc = true;
        this._clanFightDesc = value;
      }
    }

    public string ButtonDesc
    {
      get
      {
        return _buttonDesc;
      }
      set
      {
        __isset.buttonDesc = true;
        this._buttonDesc = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool title;
      public bool attackClan;
      public bool defendClan;
      public bool clanFightTableResponseList;
      public bool clanFightDesc;
      public bool buttonDesc;
    }

    public ClanFightEnterInterfaceResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Title = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              AttackClan = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              DefendClan = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                ClanFightTableResponseList = new List<ClanFightTableResponse>();
                TList _list805 = iprot.ReadListBegin();
                for( int _i806 = 0; _i806 < _list805.Count; ++_i806)
                {
                  ClanFightTableResponse _elem807 = new ClanFightTableResponse();
                  _elem807 = new ClanFightTableResponse();
                  _elem807.Read(iprot);
                  ClanFightTableResponseList.Add(_elem807);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              ClanFightDesc = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.String) {
              ButtonDesc = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ClanFightEnterInterfaceResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Title != null && __isset.title) {
        field.Name = "title";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Title);
        oprot.WriteFieldEnd();
      }
      if (__isset.attackClan) {
        field.Name = "attackClan";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(AttackClan);
        oprot.WriteFieldEnd();
      }
      if (__isset.defendClan) {
        field.Name = "defendClan";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DefendClan);
        oprot.WriteFieldEnd();
      }
      if (ClanFightTableResponseList != null && __isset.clanFightTableResponseList) {
        field.Name = "clanFightTableResponseList";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ClanFightTableResponseList.Count));
          foreach (ClanFightTableResponse _iter808 in ClanFightTableResponseList)
          {
            _iter808.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (ClanFightDesc != null && __isset.clanFightDesc) {
        field.Name = "clanFightDesc";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ClanFightDesc);
        oprot.WriteFieldEnd();
      }
      if (ButtonDesc != null && __isset.buttonDesc) {
        field.Name = "buttonDesc";
        field.Type = TType.String;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ButtonDesc);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ClanFightEnterInterfaceResponse(");
      sb.Append("Title: ");
      sb.Append(Title);
      sb.Append(",AttackClan: ");
      sb.Append(AttackClan);
      sb.Append(",DefendClan: ");
      sb.Append(DefendClan);
      sb.Append(",ClanFightTableResponseList: ");
      sb.Append(ClanFightTableResponseList);
      sb.Append(",ClanFightDesc: ");
      sb.Append(ClanFightDesc);
      sb.Append(",ButtonDesc: ");
      sb.Append(ButtonDesc);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
