/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class DungeonWarListResponse : TBase
  {
    private List<DungeonWarResponse> _listDungeonWar;

    public List<DungeonWarResponse> ListDungeonWar
    {
      get
      {
        return _listDungeonWar;
      }
      set
      {
        __isset.listDungeonWar = true;
        this._listDungeonWar = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool listDungeonWar;
    }

    public DungeonWarListResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ListDungeonWar = new List<DungeonWarResponse>();
                TList _list472 = iprot.ReadListBegin();
                for( int _i473 = 0; _i473 < _list472.Count; ++_i473)
                {
                  DungeonWarResponse _elem474 = new DungeonWarResponse();
                  _elem474 = new DungeonWarResponse();
                  _elem474.Read(iprot);
                  ListDungeonWar.Add(_elem474);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DungeonWarListResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ListDungeonWar != null && __isset.listDungeonWar) {
        field.Name = "listDungeonWar";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ListDungeonWar.Count));
          foreach (DungeonWarResponse _iter475 in ListDungeonWar)
          {
            _iter475.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("DungeonWarListResponse(");
      sb.Append("ListDungeonWar: ");
      sb.Append(ListDungeonWar);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
