/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class FunctionHintListResponse : TBase
  {
    private List<FunctionHintResponse> _listHint;

    public List<FunctionHintResponse> ListHint
    {
      get
      {
        return _listHint;
      }
      set
      {
        __isset.listHint = true;
        this._listHint = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool listHint;
    }

    public FunctionHintListResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ListHint = new List<FunctionHintResponse>();
                TList _list536 = iprot.ReadListBegin();
                for( int _i537 = 0; _i537 < _list536.Count; ++_i537)
                {
                  FunctionHintResponse _elem538 = new FunctionHintResponse();
                  _elem538 = new FunctionHintResponse();
                  _elem538.Read(iprot);
                  ListHint.Add(_elem538);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("FunctionHintListResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ListHint != null && __isset.listHint) {
        field.Name = "listHint";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ListHint.Count));
          foreach (FunctionHintResponse _iter539 in ListHint)
          {
            _iter539.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("FunctionHintListResponse(");
      sb.Append("ListHint: ");
      sb.Append(ListHint);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
