/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class ListExchangeOrdnanceResponse : TBase
  {
    private List<ExchangeOrdnanceResponse> _listOrdnance;

    public List<ExchangeOrdnanceResponse> ListOrdnance
    {
      get
      {
        return _listOrdnance;
      }
      set
      {
        __isset.listOrdnance = true;
        this._listOrdnance = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool listOrdnance;
    }

    public ListExchangeOrdnanceResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ListOrdnance = new List<ExchangeOrdnanceResponse>();
                TList _list366 = iprot.ReadListBegin();
                for( int _i367 = 0; _i367 < _list366.Count; ++_i367)
                {
                  ExchangeOrdnanceResponse _elem368 = new ExchangeOrdnanceResponse();
                  _elem368 = new ExchangeOrdnanceResponse();
                  _elem368.Read(iprot);
                  ListOrdnance.Add(_elem368);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ListExchangeOrdnanceResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ListOrdnance != null && __isset.listOrdnance) {
        field.Name = "listOrdnance";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ListOrdnance.Count));
          foreach (ExchangeOrdnanceResponse _iter369 in ListOrdnance)
          {
            _iter369.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ListExchangeOrdnanceResponse(");
      sb.Append("ListOrdnance: ");
      sb.Append(ListOrdnance);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
