/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class NinePayResponse : TBase
  {
    private string _cooOrderSerial;

    public string CooOrderSerial
    {
      get
      {
        return _cooOrderSerial;
      }
      set
      {
        __isset.cooOrderSerial = true;
        this._cooOrderSerial = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool cooOrderSerial;
    }

    public NinePayResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              CooOrderSerial = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NinePayResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CooOrderSerial != null && __isset.cooOrderSerial) {
        field.Name = "cooOrderSerial";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CooOrderSerial);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NinePayResponse(");
      sb.Append("CooOrderSerial: ");
      sb.Append(CooOrderSerial);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
