/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PersonsDungeonPlayersListResponse : TBase
  {
    private int _dungeon_id;
    private int _dungeon_instance_id;
    private int _user_id;
    private List<PersonsDungeonPlayersResponse> _listPlayer;

    public int Dungeon_id
    {
      get
      {
        return _dungeon_id;
      }
      set
      {
        __isset.dungeon_id = true;
        this._dungeon_id = value;
      }
    }

    public int Dungeon_instance_id
    {
      get
      {
        return _dungeon_instance_id;
      }
      set
      {
        __isset.dungeon_instance_id = true;
        this._dungeon_instance_id = value;
      }
    }

    public int User_id
    {
      get
      {
        return _user_id;
      }
      set
      {
        __isset.user_id = true;
        this._user_id = value;
      }
    }

    public List<PersonsDungeonPlayersResponse> ListPlayer
    {
      get
      {
        return _listPlayer;
      }
      set
      {
        __isset.listPlayer = true;
        this._listPlayer = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool dungeon_id;
      public bool dungeon_instance_id;
      public bool user_id;
      public bool listPlayer;
    }

    public PersonsDungeonPlayersListResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              Dungeon_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Dungeon_instance_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              User_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.List) {
              {
                ListPlayer = new List<PersonsDungeonPlayersResponse>();
                TList _list468 = iprot.ReadListBegin();
                for( int _i469 = 0; _i469 < _list468.Count; ++_i469)
                {
                  PersonsDungeonPlayersResponse _elem470 = new PersonsDungeonPlayersResponse();
                  _elem470 = new PersonsDungeonPlayersResponse();
                  _elem470.Read(iprot);
                  ListPlayer.Add(_elem470);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PersonsDungeonPlayersListResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.dungeon_id) {
        field.Name = "dungeon_id";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Dungeon_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.dungeon_instance_id) {
        field.Name = "dungeon_instance_id";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Dungeon_instance_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.user_id) {
        field.Name = "user_id";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(User_id);
        oprot.WriteFieldEnd();
      }
      if (ListPlayer != null && __isset.listPlayer) {
        field.Name = "listPlayer";
        field.Type = TType.List;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ListPlayer.Count));
          foreach (PersonsDungeonPlayersResponse _iter471 in ListPlayer)
          {
            _iter471.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PersonsDungeonPlayersListResponse(");
      sb.Append("Dungeon_id: ");
      sb.Append(Dungeon_id);
      sb.Append(",Dungeon_instance_id: ");
      sb.Append(Dungeon_instance_id);
      sb.Append(",User_id: ");
      sb.Append(User_id);
      sb.Append(",ListPlayer: ");
      sb.Append(ListPlayer);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
