/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PlayerYiJianOrdnanceBagResponse : TBase
  {
    private List<OrdnanceBagResponse> _PlayerOrdnanceBag;

    public List<OrdnanceBagResponse> PlayerOrdnanceBag
    {
      get
      {
        return _PlayerOrdnanceBag;
      }
      set
      {
        __isset.PlayerOrdnanceBag = true;
        this._PlayerOrdnanceBag = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool PlayerOrdnanceBag;
    }

    public PlayerYiJianOrdnanceBagResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                PlayerOrdnanceBag = new List<OrdnanceBagResponse>();
                TList _list349 = iprot.ReadListBegin();
                for( int _i350 = 0; _i350 < _list349.Count; ++_i350)
                {
                  OrdnanceBagResponse _elem351 = new OrdnanceBagResponse();
                  _elem351 = new OrdnanceBagResponse();
                  _elem351.Read(iprot);
                  PlayerOrdnanceBag.Add(_elem351);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerYiJianOrdnanceBagResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (PlayerOrdnanceBag != null && __isset.PlayerOrdnanceBag) {
        field.Name = "PlayerOrdnanceBag";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, PlayerOrdnanceBag.Count));
          foreach (OrdnanceBagResponse _iter352 in PlayerOrdnanceBag)
          {
            _iter352.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerYiJianOrdnanceBagResponse(");
      sb.Append("PlayerOrdnanceBag: ");
      sb.Append(PlayerOrdnanceBag);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
