/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PlayerBagItemsUpdateListResponse : TBase
  {
    private List<PlayerBagItemUpdateResponse> _itemsList;

    public List<PlayerBagItemUpdateResponse> ItemsList
    {
      get
      {
        return _itemsList;
      }
      set
      {
        __isset.itemsList = true;
        this._itemsList = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool itemsList;
    }

    public PlayerBagItemsUpdateListResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ItemsList = new List<PlayerBagItemUpdateResponse>();
                TList _list68 = iprot.ReadListBegin();
                for( int _i69 = 0; _i69 < _list68.Count; ++_i69)
                {
                  PlayerBagItemUpdateResponse _elem70 = new PlayerBagItemUpdateResponse();
                  _elem70 = new PlayerBagItemUpdateResponse();
                  _elem70.Read(iprot);
                  ItemsList.Add(_elem70);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerBagItemsUpdateListResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ItemsList != null && __isset.itemsList) {
        field.Name = "itemsList";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ItemsList.Count));
          foreach (PlayerBagItemUpdateResponse _iter71 in ItemsList)
          {
            _iter71.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerBagItemsUpdateListResponse(");
      sb.Append("ItemsList: ");
      sb.Append(ItemsList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
