/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PlayerClanKnowledgeResponse : TBase
  {
    private List<ClanKnowledgeResponse> _clanKnowledgeResponseList;
    private int _speedUseTime;

    public List<ClanKnowledgeResponse> ClanKnowledgeResponseList
    {
      get
      {
        return _clanKnowledgeResponseList;
      }
      set
      {
        __isset.clanKnowledgeResponseList = true;
        this._clanKnowledgeResponseList = value;
      }
    }

    public int SpeedUseTime
    {
      get
      {
        return _speedUseTime;
      }
      set
      {
        __isset.speedUseTime = true;
        this._speedUseTime = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool clanKnowledgeResponseList;
      public bool speedUseTime;
    }

    public PlayerClanKnowledgeResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ClanKnowledgeResponseList = new List<ClanKnowledgeResponse>();
                TList _list777 = iprot.ReadListBegin();
                for( int _i778 = 0; _i778 < _list777.Count; ++_i778)
                {
                  ClanKnowledgeResponse _elem779 = new ClanKnowledgeResponse();
                  _elem779 = new ClanKnowledgeResponse();
                  _elem779.Read(iprot);
                  ClanKnowledgeResponseList.Add(_elem779);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              SpeedUseTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerClanKnowledgeResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ClanKnowledgeResponseList != null && __isset.clanKnowledgeResponseList) {
        field.Name = "clanKnowledgeResponseList";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ClanKnowledgeResponseList.Count));
          foreach (ClanKnowledgeResponse _iter780 in ClanKnowledgeResponseList)
          {
            _iter780.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.speedUseTime) {
        field.Name = "speedUseTime";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SpeedUseTime);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerClanKnowledgeResponse(");
      sb.Append("ClanKnowledgeResponseList: ");
      sb.Append(ClanKnowledgeResponseList);
      sb.Append(",SpeedUseTime: ");
      sb.Append(SpeedUseTime);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
