/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PlayerTreasuryResponse : TBase
  {
    private List<PlunderPlayerResponse> _playerList;

    public List<PlunderPlayerResponse> PlayerList
    {
      get
      {
        return _playerList;
      }
      set
      {
        __isset.playerList = true;
        this._playerList = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool playerList;
    }

    public PlayerTreasuryResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                PlayerList = new List<PlunderPlayerResponse>();
                TList _list528 = iprot.ReadListBegin();
                for( int _i529 = 0; _i529 < _list528.Count; ++_i529)
                {
                  PlunderPlayerResponse _elem530 = new PlunderPlayerResponse();
                  _elem530 = new PlunderPlayerResponse();
                  _elem530.Read(iprot);
                  PlayerList.Add(_elem530);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerTreasuryResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (PlayerList != null && __isset.playerList) {
        field.Name = "playerList";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, PlayerList.Count));
          foreach (PlunderPlayerResponse _iter531 in PlayerList)
          {
            _iter531.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerTreasuryResponse(");
      sb.Append("PlayerList: ");
      sb.Append(PlayerList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
