/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PlayerSchemeBagRequest : TBase
  {
    private byte _type;
    private int _scheme_id;
    private int _instance_id;
    private List<int> _scheme_id_list;
    private string _scheme_version;

    public byte Type
    {
      get
      {
        return _type;
      }
      set
      {
        __isset.type = true;
        this._type = value;
      }
    }

    public int Scheme_id
    {
      get
      {
        return _scheme_id;
      }
      set
      {
        __isset.scheme_id = true;
        this._scheme_id = value;
      }
    }

    public int Instance_id
    {
      get
      {
        return _instance_id;
      }
      set
      {
        __isset.instance_id = true;
        this._instance_id = value;
      }
    }

    public List<int> Scheme_id_list
    {
      get
      {
        return _scheme_id_list;
      }
      set
      {
        __isset.scheme_id_list = true;
        this._scheme_id_list = value;
      }
    }

    public string Scheme_version
    {
      get
      {
        return _scheme_version;
      }
      set
      {
        __isset.scheme_version = true;
        this._scheme_version = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool type;
      public bool scheme_id;
      public bool instance_id;
      public bool scheme_id_list;
      public bool scheme_version;
    }

    public PlayerSchemeBagRequest() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Byte) {
              Type = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Scheme_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              Instance_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.List) {
              {
                Scheme_id_list = new List<int>();
                TList _list640 = iprot.ReadListBegin();
                for( int _i641 = 0; _i641 < _list640.Count; ++_i641)
                {
                  int _elem642 = 0;
                  _elem642 = iprot.ReadI32();
                  Scheme_id_list.Add(_elem642);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              Scheme_version = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerSchemeBagRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.type) {
        field.Name = "type";
        field.Type = TType.Byte;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Type);
        oprot.WriteFieldEnd();
      }
      if (__isset.scheme_id) {
        field.Name = "scheme_id";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Scheme_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.instance_id) {
        field.Name = "instance_id";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Instance_id);
        oprot.WriteFieldEnd();
      }
      if (Scheme_id_list != null && __isset.scheme_id_list) {
        field.Name = "scheme_id_list";
        field.Type = TType.List;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I32, Scheme_id_list.Count));
          foreach (int _iter643 in Scheme_id_list)
          {
            oprot.WriteI32(_iter643);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Scheme_version != null && __isset.scheme_version) {
        field.Name = "scheme_version";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Scheme_version);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerSchemeBagRequest(");
      sb.Append("Type: ");
      sb.Append(Type);
      sb.Append(",Scheme_id: ");
      sb.Append(Scheme_id);
      sb.Append(",Instance_id: ");
      sb.Append(Instance_id);
      sb.Append(",Scheme_id_list: ");
      sb.Append(Scheme_id_list);
      sb.Append(",Scheme_version: ");
      sb.Append(Scheme_version);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
