/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class PlayerStarBagRequest : TBase
  {
    private byte _type;
    private int _instance_id;
    private int _star_id;
    private int _general_id;
    private int _synthetize_num;
    private int _protection;
    private int _wish;
    private bool _isBuyProtection;
    private bool _isBuyWish;
    private int _automatic_num;

    public byte Type
    {
      get
      {
        return _type;
      }
      set
      {
        __isset.type = true;
        this._type = value;
      }
    }

    public int Instance_id
    {
      get
      {
        return _instance_id;
      }
      set
      {
        __isset.instance_id = true;
        this._instance_id = value;
      }
    }

    public int Star_id
    {
      get
      {
        return _star_id;
      }
      set
      {
        __isset.star_id = true;
        this._star_id = value;
      }
    }

    public int General_id
    {
      get
      {
        return _general_id;
      }
      set
      {
        __isset.general_id = true;
        this._general_id = value;
      }
    }

    public int Synthetize_num
    {
      get
      {
        return _synthetize_num;
      }
      set
      {
        __isset.synthetize_num = true;
        this._synthetize_num = value;
      }
    }

    public int Protection
    {
      get
      {
        return _protection;
      }
      set
      {
        __isset.protection = true;
        this._protection = value;
      }
    }

    public int Wish
    {
      get
      {
        return _wish;
      }
      set
      {
        __isset.wish = true;
        this._wish = value;
      }
    }

    public bool IsBuyProtection
    {
      get
      {
        return _isBuyProtection;
      }
      set
      {
        __isset.isBuyProtection = true;
        this._isBuyProtection = value;
      }
    }

    public bool IsBuyWish
    {
      get
      {
        return _isBuyWish;
      }
      set
      {
        __isset.isBuyWish = true;
        this._isBuyWish = value;
      }
    }

    public int Automatic_num
    {
      get
      {
        return _automatic_num;
      }
      set
      {
        __isset.automatic_num = true;
        this._automatic_num = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool type;
      public bool instance_id;
      public bool star_id;
      public bool general_id;
      public bool synthetize_num;
      public bool protection;
      public bool wish;
      public bool isBuyProtection;
      public bool isBuyWish;
      public bool automatic_num;
    }

    public PlayerStarBagRequest() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Byte) {
              Type = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              Instance_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              Star_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              General_id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              Synthetize_num = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              Protection = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              Wish = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.Bool) {
              IsBuyProtection = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.Bool) {
              IsBuyWish = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              Automatic_num = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PlayerStarBagRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.type) {
        field.Name = "type";
        field.Type = TType.Byte;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Type);
        oprot.WriteFieldEnd();
      }
      if (__isset.instance_id) {
        field.Name = "instance_id";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Instance_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.star_id) {
        field.Name = "star_id";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Star_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.general_id) {
        field.Name = "general_id";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(General_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.synthetize_num) {
        field.Name = "synthetize_num";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Synthetize_num);
        oprot.WriteFieldEnd();
      }
      if (__isset.protection) {
        field.Name = "protection";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Protection);
        oprot.WriteFieldEnd();
      }
      if (__isset.wish) {
        field.Name = "wish";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Wish);
        oprot.WriteFieldEnd();
      }
      if (__isset.isBuyProtection) {
        field.Name = "isBuyProtection";
        field.Type = TType.Bool;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(IsBuyProtection);
        oprot.WriteFieldEnd();
      }
      if (__isset.isBuyWish) {
        field.Name = "isBuyWish";
        field.Type = TType.Bool;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(IsBuyWish);
        oprot.WriteFieldEnd();
      }
      if (__isset.automatic_num) {
        field.Name = "automatic_num";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Automatic_num);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("PlayerStarBagRequest(");
      sb.Append("Type: ");
      sb.Append(Type);
      sb.Append(",Instance_id: ");
      sb.Append(Instance_id);
      sb.Append(",Star_id: ");
      sb.Append(Star_id);
      sb.Append(",General_id: ");
      sb.Append(General_id);
      sb.Append(",Synthetize_num: ");
      sb.Append(Synthetize_num);
      sb.Append(",Protection: ");
      sb.Append(Protection);
      sb.Append(",Wish: ");
      sb.Append(Wish);
      sb.Append(",IsBuyProtection: ");
      sb.Append(IsBuyProtection);
      sb.Append(",IsBuyWish: ");
      sb.Append(IsBuyWish);
      sb.Append(",Automatic_num: ");
      sb.Append(Automatic_num);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
