/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class QuestProgressResponse : TBase
  {
    private byte _type;
    private int _questID;
    private byte _questType;
    private string _questName;
    private string _questTargetProgressDesc;
    private int _times;
    private int _neendGold;
    private byte _questState;

    public byte Type
    {
      get
      {
        return _type;
      }
      set
      {
        __isset.type = true;
        this._type = value;
      }
    }

    public int QuestID
    {
      get
      {
        return _questID;
      }
      set
      {
        __isset.questID = true;
        this._questID = value;
      }
    }

    public byte QuestType
    {
      get
      {
        return _questType;
      }
      set
      {
        __isset.questType = true;
        this._questType = value;
      }
    }

    public string QuestName
    {
      get
      {
        return _questName;
      }
      set
      {
        __isset.questName = true;
        this._questName = value;
      }
    }

    public string QuestTargetProgressDesc
    {
      get
      {
        return _questTargetProgressDesc;
      }
      set
      {
        __isset.questTargetProgressDesc = true;
        this._questTargetProgressDesc = value;
      }
    }

    public int Times
    {
      get
      {
        return _times;
      }
      set
      {
        __isset.times = true;
        this._times = value;
      }
    }

    public int NeendGold
    {
      get
      {
        return _neendGold;
      }
      set
      {
        __isset.neendGold = true;
        this._neendGold = value;
      }
    }

    public byte QuestState
    {
      get
      {
        return _questState;
      }
      set
      {
        __isset.questState = true;
        this._questState = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool type;
      public bool questID;
      public bool questType;
      public bool questName;
      public bool questTargetProgressDesc;
      public bool times;
      public bool neendGold;
      public bool questState;
    }

    public QuestProgressResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Byte) {
              Type = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              QuestID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Byte) {
              QuestType = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              QuestName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.String) {
              QuestTargetProgressDesc = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I32) {
              Times = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I32) {
              NeendGold = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.Byte) {
              QuestState = iprot.ReadByte();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("QuestProgressResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.type) {
        field.Name = "type";
        field.Type = TType.Byte;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(Type);
        oprot.WriteFieldEnd();
      }
      if (__isset.questID) {
        field.Name = "questID";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(QuestID);
        oprot.WriteFieldEnd();
      }
      if (__isset.questType) {
        field.Name = "questType";
        field.Type = TType.Byte;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(QuestType);
        oprot.WriteFieldEnd();
      }
      if (QuestName != null && __isset.questName) {
        field.Name = "questName";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(QuestName);
        oprot.WriteFieldEnd();
      }
      if (QuestTargetProgressDesc != null && __isset.questTargetProgressDesc) {
        field.Name = "questTargetProgressDesc";
        field.Type = TType.String;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(QuestTargetProgressDesc);
        oprot.WriteFieldEnd();
      }
      if (__isset.times) {
        field.Name = "times";
        field.Type = TType.I32;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Times);
        oprot.WriteFieldEnd();
      }
      if (__isset.neendGold) {
        field.Name = "neendGold";
        field.Type = TType.I32;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(NeendGold);
        oprot.WriteFieldEnd();
      }
      if (__isset.questState) {
        field.Name = "questState";
        field.Type = TType.Byte;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        oprot.WriteByte(QuestState);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("QuestProgressResponse(");
      sb.Append("Type: ");
      sb.Append(Type);
      sb.Append(",QuestID: ");
      sb.Append(QuestID);
      sb.Append(",QuestType: ");
      sb.Append(QuestType);
      sb.Append(",QuestName: ");
      sb.Append(QuestName);
      sb.Append(",QuestTargetProgressDesc: ");
      sb.Append(QuestTargetProgressDesc);
      sb.Append(",Times: ");
      sb.Append(Times);
      sb.Append(",NeendGold: ");
      sb.Append(NeendGold);
      sb.Append(",QuestState: ");
      sb.Append(QuestState);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
