/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace com.think.messages
{

  [Serializable]
  public partial class ServiceProblemListResponse : TBase
  {
    private List<ServiceProblemResponse> _serviceProblemList;

    public List<ServiceProblemResponse> ServiceProblemList
    {
      get
      {
        return _serviceProblemList;
      }
      set
      {
        __isset.serviceProblemList = true;
        this._serviceProblemList = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool serviceProblemList;
    }

    public ServiceProblemListResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                ServiceProblemList = new List<ServiceProblemResponse>();
                TList _list441 = iprot.ReadListBegin();
                for( int _i442 = 0; _i442 < _list441.Count; ++_i442)
                {
                  ServiceProblemResponse _elem443 = new ServiceProblemResponse();
                  _elem443 = new ServiceProblemResponse();
                  _elem443.Read(iprot);
                  ServiceProblemList.Add(_elem443);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ServiceProblemListResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ServiceProblemList != null && __isset.serviceProblemList) {
        field.Name = "serviceProblemList";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, ServiceProblemList.Count));
          foreach (ServiceProblemResponse _iter444 in ServiceProblemList)
          {
            _iter444.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ServiceProblemListResponse(");
      sb.Append("ServiceProblemList: ");
      sb.Append(ServiceProblemList);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
